### PR TITLE
Bunch of performance optimizations and standards cleanup

### PR DESCRIPTION
**Pull request by dhershman1**
# Changelog

- Cleaned up drastic amounts to fit better standards and guidelines
- Fixed some doc comments
- Dropped bluebird dependency for internal promises for better performance
- Moved a lot of variable sets into their proper blocks since `const` and `let` are block scoped 
- Dropped `for of` loops in favor of the built in iterable functionality like `forEach`
- Wrapped loadHelpers in a function to keep it contained and out of the global logic
- Dropped custom file crawling and mashing together in favor of using built in handlebars functionality
- Removed loadFiles function since it's no longer needed/used
- Simplified the logic of main module function

### CODE REVIEW

**Comment by ConnorWiseman** [comment]
I like this a lot! Seriously, awesome contribution. A few questions, though, because I want to understand what's going on here. Apologies-- I'm a student, and I've still got a lot to learn.

* This will automatically register all partials upon application startup, correct?

When I originally wrote this module, I intended to let the module handle partial caching and manually pass them around outside of the Handlebars environment. Registering them directly with the Handlebars environment makes a lot more sense from an implementation perspective, but unless I misunderstand, the caching of partials is no longer a possibility. Kludgy as it was, it was a kind of nice feature for development.

* I guess what I'm asking is, is there any actual reason to keep partials in some sort of manual in-memory store? Or better yet, is there a way of invalidating/unregistering/reregistering partials with the Handlebars environment to sort of merge both features?

I don't think I've ever encountered `@return {Undefined}`. I'm more used to Google's Closure Compiler's ["suggested" way of doing things](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#return-type-description), where the absence of a `@return` directive hints that the function returns nothing worth noting.

* Are there more popular/more widely understood ways of using JSDoc with Node.js? I'd like to give those a read, if you'd be kind enough to point them out to me.

I notice you removed the `options` / `viewOpts` from `renderView`. I remember delving into the Handlebars template API and the source code back when I originally wrote this but I can't find my notes about what those parameters did and I can't find a reference to them in the docs/don't have the time to peruse the source now.

* Do you know, offhand, if removing that would cause any sort of breakage in projects using this module? I'm kicking myself now for not writing tests for it!

I'm not super sure about removing the dependency on Bluebird being an optimization improvement. I don't like including an extra dependency for what will soon amount to one or two Promises, but by all accounts, it really does perform better than ES6's native Promises. Here are the results of [Bluebird's benchmarking suites](http://bluebirdjs.com/docs/contribute.html#benchmarking) as performed on my not-so-great school laptop as of a few minutes ago:

```
results for 10000 parallel executions, 1 ms per I/O op

file                                       time(ms)  memory(MB)
callbacks-baseline.js                           118       31.20
callbacks-suguru03-neo-async-waterfall.js       154       39.42
promises-bluebird-generator.js                  333       41.64
promises-bluebird.js                            360       47.89
promises-cujojs-when.js                         500       60.83
promises-tildeio-rsvp.js                        514       75.75
promises-then-promise.js                        546       70.25
promises-lvivski-davy.js                        568      100.04
promises-ecmascript6-native.js                  706      106.06
generators-tj-co.js                             788       76.30
callbacks-caolan-async-waterfall.js             806      108.64
promises-dfilatov-vow.js                        916      141.32
promises-calvinmetcalf-lie.js                  1286      169.37
promises-obvious-kew.js                        1363      233.19
streamline-generators.js                       1473      153.02
promises-medikoo-deferred.js                   1485      182.77
streamline-callbacks.js                        1961      192.52
observables-pozadi-kefir.js                    2106      203.80
observables-Reactive-Extensions-RxJS.js        3681      235.17
promises-kriskowal-q.js                       14203      358.06
observables-caolan-highland.js                14445      552.85
observables-baconjs-bacon.js.js               37067      918.36


results for 10000 parallel executions, 1 ms per I/O op

file                                      time(ms)  memory(MB)
callbacks-baseline.js                          410       72.61
callbacks-suguru03-neo-async-parallel.js       547       88.91
promises-bluebird.js                           688      108.53
promises-bluebird-generator.js                 714      112.67
promises-lvivski-davy.js                       904      176.83
callbacks-caolan-async-parallel.js             937      156.30
promises-cujojs-when.js                       1044      170.48
promises-ecmascript6-native.js                1813      310.83
promises-tildeio-rsvp.js                      1938      355.48
promises-then-promise.js                      2801      301.33
promises-calvinmetcalf-lie.js                 2941      378.01
promises-medikoo-deferred.js                  2972      367.60
promises-dfilatov-vow.js                      3372      565.84
promises-obvious-kew.js                       4953      711.16
streamline-generators.js                     17783      988.43
streamline-callbacks.js                      31590     1193.69


Platform info:
Windows_NT 10.0.15063 x64
Node.JS 8.1.3
V8 5.8.283.41
Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz × 4
```

However, I think what you've suggested here is a great step toward getting rid of Promises entirely.

* With just one/two in the mix, why not go the rest of the way and just use callbacks internally? Those perform much better than anything else on the list.

* I don't know, honestly. Thoughts? Would it even be practical to rely on callbacks within an `async` function to handle template rendering?

**Comment by dhershman1** [comment]
To your first question, it should work the same as it did before just instead it's using handlebars functionality to register the partials instead of planting them into templates. If the path they give turns up more than one helper then it should grab all of them in that file so long as they are .hbs or whatever the extension they're using is. 

There is no ability to un register or re register but it should still be using cache if needed when needed (if you look at the integration tests) I can continue to play around with this to verify my thoughts.

As for jsDocs I highly recommend you use the docBlockr plugin for your editor it is on both Atom.io (what I use) and sublime text. 

`options`, `viewOpts` seemed to only be passing partials information to the layout/view render function. They can easily be put back in if you'd prefer it.

Having Bluebird as a dependency increases both the number of packages your module is using, and the overall size of the package itself. However you are correct that Bluebird is more performant than the native library. I'd rather us use promises than callbacks since they make everything easier to read that's your call. I just prefer native for less worry about the dependencies behind my modules. I also see the benefit of using Bluebird however, so the choice is yours.

**Comment by dhershman1** [comment]
Adding onto what I said, the main reason bluebirds much faster than native promises, is because in it's source bluebird is simply just wrapping callbacks, and like you mentioned callbacks are always faster than promises.

EDIT: I have yet to ever run into an issue where native promises are my bottleneck however

**Comment by ConnorWiseman** [comment]
Well... views and layouts get hit on the cache when they're being served, but partials aren't ever stored there; they're just registered with the Handlebars environment. I'm betting that that's the better way to do it, but it's unfortunate that once the application gets fired up, edits to partials won't filter through without a restart. I suppose that's what things like `nodemon` or `pm2` are for, though.

I do use the docBlockr plugin, and I love that thing! I've yet to have it suggest `@return {Undefined}`, however. 

That part about Promises not being a bottleneck is a fair point and is, I think, the best argument against keeping Bluebird even if it's a little quicker.

**Comment by ConnorWiseman** [comment]
Blargh. Been living in a place without WiFi for a while now.

**Pull request merged**
